-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 22:50:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresas` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Choferes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Choferes` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `idChofer` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idChofer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculos_Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculos_Transporte` (
  `placa` VARCHAR(6) NOT NULL,
  `cantidad_viajes` INT NULL,
  `volumen_carga` DECIMAL(15) NULL,
  `volumen_transportado` DECIMAL(15) NULL,
  `costo_acarreo` DECIMAL(15) NULL,
  `Empresa_idEmpresa` INT NULL,
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `Choferes_idChofer` INT NOT NULL,
  PRIMARY KEY (`idVehiculo`),
  CONSTRAINT `fk_Vehiculos_Transporte_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `mydb`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculos_Transporte_Choferes1`
    FOREIGN KEY (`Choferes_idChofer`)
    REFERENCES `mydb`.`Choferes` (`idChofer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vehiculos_Transporte_Empresa1_idx` ON `mydb`.`Vehiculos_Transporte` (`Empresa_idEmpresa` ASC);

CREATE INDEX `fk_Vehiculos_Transporte_Choferes1_idx` ON `mydb`.`Vehiculos_Transporte` (`Choferes_idChofer` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materiales` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `compactacion` DECIMAL(5) NULL,
  `llenado` DECIMAL(15) NULL,
  `excavado` VARCHAR(45) NULL,
  `cantidad` DECIMAL(20) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abscisas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abscisas` (
  `descripcion` VARCHAR(45) NOT NULL,
  `idAbscisa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAbscisa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abscisa_Origen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abscisa_Origen` (
  `idAbscisa_Origen` INT NOT NULL AUTO_INCREMENT,
  `Abscisas_idAbscisa` INT NOT NULL,
  PRIMARY KEY (`idAbscisa_Origen`),
  CONSTRAINT `fk_Abscisa_Origen_Abscisas1`
    FOREIGN KEY (`Abscisas_idAbscisa`)
    REFERENCES `mydb`.`Abscisas` (`idAbscisa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Abscisa_Origen_Abscisas1_idx` ON `mydb`.`Abscisa_Origen` (`Abscisas_idAbscisa` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Abscisa_destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abscisa_destino` (
  `idAbscisa_destino` INT NOT NULL AUTO_INCREMENT,
  `Abscisas_idAbscisa1` INT NOT NULL,
  PRIMARY KEY (`idAbscisa_destino`),
  CONSTRAINT `fk_Abscisa_destino_Abscisas1`
    FOREIGN KEY (`Abscisas_idAbscisa1`)
    REFERENCES `mydb`.`Abscisas` (`idAbscisa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Abscisa_destino_Abscisas1_idx` ON `mydb`.`Abscisa_destino` (`Abscisas_idAbscisa1` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo_Transporte_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo_Transporte_Material` (
  `fecha` DATE NOT NULL,
  `numeroRecibo` INT NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  `Vehiculos_Transporte_idVehiculo` INT NOT NULL,
  `Materiales_idMaterial` INT NOT NULL,
  `Abscisa_Origen_idAbscisa_Origen` INT NOT NULL,
  `Abscisa_destino_idAbscisa_destino` INT NOT NULL,
  PRIMARY KEY (`numeroRecibo`),
  CONSTRAINT `fk_Vehiculo_Transporte_Material_Vehiculos_Transporte1`
    FOREIGN KEY (`Vehiculos_Transporte_idVehiculo`)
    REFERENCES `mydb`.`Vehiculos_Transporte` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Transporte_Material_Materiales1`
    FOREIGN KEY (`Materiales_idMaterial`)
    REFERENCES `mydb`.`Materiales` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Transporte_Material_Abscisa_Origen1`
    FOREIGN KEY (`Abscisa_Origen_idAbscisa_Origen`)
    REFERENCES `mydb`.`Abscisa_Origen` (`idAbscisa_Origen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Transporte_Material_Abscisa_destino1`
    FOREIGN KEY (`Abscisa_destino_idAbscisa_destino`)
    REFERENCES `mydb`.`Abscisa_destino` (`idAbscisa_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vehiculo_Transporte_Material_Vehiculos_Transporte1_idx` ON `mydb`.`Vehiculo_Transporte_Material` (`Vehiculos_Transporte_idVehiculo` ASC);

CREATE INDEX `fk_Vehiculo_Transporte_Material_Materiales1_idx` ON `mydb`.`Vehiculo_Transporte_Material` (`Materiales_idMaterial` ASC);

CREATE INDEX `fk_Vehiculo_Transporte_Material_Abscisa_Origen1_idx` ON `mydb`.`Vehiculo_Transporte_Material` (`Abscisa_Origen_idAbscisa_Origen` ASC);

CREATE INDEX `fk_Vehiculo_Transporte_Material_Abscisa_destino1_idx` ON `mydb`.`Vehiculo_Transporte_Material` (`Abscisa_destino_idAbscisa_destino` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `name` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
